owner: SagentsCTO
repo: writingdesk-status

sites:
  - name: WritingDesk (Prod)
    url: https://writingdesk.13apples.com
  - name: WritingDesk (Test)
    url: https://testwritingdesk.13apples.com
  - name: WritingDesk Lite
    url: https://writingdesklite.13apples.com
  - name: PropertyLens
    url: https://propertylens.13apples.com/this-will-404-test

status-website:
  name: WritingDesk Status
  introTitle: WritingDesk System Status
  baseUrl: "/writingdesk-status"
